package com.huaruan.shop.bo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table productinfo
 *
 * @mbg.generated do_not_delete_during_merge Mon Jan 07 13:03:39 CST 2019
 */
public class ProductInfoBO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.id
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.productname
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private String productname;

    /**
     * Database Column Remarks:
     *   价格(单位:分)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.price
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Integer price;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.number
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Integer number;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.product_desc
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private String productDesc;

    /**
     * Database Column Remarks:
     *   商品图片id ,隔开
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.product_pic_id
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private String productPicId;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.vendorid
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Long vendorid;

    /**
     * Database Column Remarks:
     *   运费(单位:分)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.postage
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Integer postage;

    /**
     * Database Column Remarks:
     *   状态 0售罄 1在库 2下架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.status
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private String status;

    /**
     * Database Column Remarks:
     *   生成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.create_time
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.update_time
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   评价id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.commentid
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private Long commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.id
     *
     * @return the value of productinfo.id
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.id
     *
     * @param id the value for productinfo.id
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.productname
     *
     * @return the value of productinfo.productname
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.productname
     *
     * @param productname the value for productinfo.productname
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.price
     *
     * @return the value of productinfo.price
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.price
     *
     * @param price the value for productinfo.price
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.number
     *
     * @return the value of productinfo.number
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.number
     *
     * @param number the value for productinfo.number
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.product_desc
     *
     * @return the value of productinfo.product_desc
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.product_desc
     *
     * @param productDesc the value for productinfo.product_desc
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.product_pic_id
     *
     * @return the value of productinfo.product_pic_id
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public String getProductPicId() {
        return productPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.product_pic_id
     *
     * @param productPicId the value for productinfo.product_pic_id
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setProductPicId(String productPicId) {
        this.productPicId = productPicId == null ? null : productPicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.vendorid
     *
     * @return the value of productinfo.vendorid
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Long getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.vendorid
     *
     * @param vendorid the value for productinfo.vendorid
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setVendorid(Long vendorid) {
        this.vendorid = vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.postage
     *
     * @return the value of productinfo.postage
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.postage
     *
     * @param postage the value for productinfo.postage
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.status
     *
     * @return the value of productinfo.status
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.status
     *
     * @param status the value for productinfo.status
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.create_time
     *
     * @return the value of productinfo.create_time
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.create_time
     *
     * @param createTime the value for productinfo.create_time
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.update_time
     *
     * @return the value of productinfo.update_time
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.update_time
     *
     * @param updateTime the value for productinfo.update_time
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.commentid
     *
     * @return the value of productinfo.commentid
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public Long getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.commentid
     *
     * @param commentid the value for productinfo.commentid
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    public void setCommentid(Long commentid) {
        this.commentid = commentid;
    }
}