package com.huaruan.shop.bo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_order
 *
 * @mbg.generated do_not_delete_during_merge Sun Jan 27 16:49:22 CST 2019
 */
public class SysOrderBO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.vendor_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Long vendorId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.user_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.product_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   商品名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.product_name
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   商品金额(单位:分)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.product_cash
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Integer productCash;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.product_num
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Integer productNum;

    /**
     * Database Column Remarks:
     *   订单状态 1交易成功 2交易关闭 3未付款 4配送中
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.status
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private String status;

    /**
     * Database Column Remarks:
     *   运费(单位:分)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.postage
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Integer postage;

    /**
     * Database Column Remarks:
     *   收货地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.adress
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private String adress;

    /**
     * Database Column Remarks:
     *   收货人名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.receiver_name
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private String receiverName;

    /**
     * Database Column Remarks:
     *   生成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.create_time
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.update_time
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.id
     *
     * @return the value of sys_order.id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.id
     *
     * @param id the value for sys_order.id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.vendor_id
     *
     * @return the value of sys_order.vendor_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Long getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.vendor_id
     *
     * @param vendorId the value for sys_order.vendor_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.user_id
     *
     * @return the value of sys_order.user_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.user_id
     *
     * @param userId the value for sys_order.user_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.product_id
     *
     * @return the value of sys_order.product_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.product_id
     *
     * @param productId the value for sys_order.product_id
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.product_name
     *
     * @return the value of sys_order.product_name
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.product_name
     *
     * @param productName the value for sys_order.product_name
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.product_cash
     *
     * @return the value of sys_order.product_cash
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Integer getProductCash() {
        return productCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.product_cash
     *
     * @param productCash the value for sys_order.product_cash
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setProductCash(Integer productCash) {
        this.productCash = productCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.product_num
     *
     * @return the value of sys_order.product_num
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.product_num
     *
     * @param productNum the value for sys_order.product_num
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.status
     *
     * @return the value of sys_order.status
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.status
     *
     * @param status the value for sys_order.status
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.postage
     *
     * @return the value of sys_order.postage
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.postage
     *
     * @param postage the value for sys_order.postage
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.adress
     *
     * @return the value of sys_order.adress
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.adress
     *
     * @param adress the value for sys_order.adress
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.receiver_name
     *
     * @return the value of sys_order.receiver_name
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.receiver_name
     *
     * @param receiverName the value for sys_order.receiver_name
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.create_time
     *
     * @return the value of sys_order.create_time
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.create_time
     *
     * @param createTime the value for sys_order.create_time
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_order.update_time
     *
     * @return the value of sys_order.update_time
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_order.update_time
     *
     * @param updateTime the value for sys_order.update_time
     *
     * @mbg.generated Sun Jan 27 16:49:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}