package com.huaruan.shop.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comment
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 19 21:03:42 CST 2019
 */
public class CommentDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.vendorid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private Long vendorid;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private Long userid;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.productid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private Long productid;

    /**
     * Database Column Remarks:
     *   评论内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private String content;

    /**
     * Database Column Remarks:
     *   发送人 1商户 2用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.senderType
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private String sendertype;

    /**
     * Database Column Remarks:
     *   生成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.update_time
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.vendorid
     *
     * @return the value of comment.vendorid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public Long getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.vendorid
     *
     * @param vendorid the value for comment.vendorid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setVendorid(Long vendorid) {
        this.vendorid = vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.productid
     *
     * @return the value of comment.productid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.productid
     *
     * @param productid the value for comment.productid
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.senderType
     *
     * @return the value of comment.senderType
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public String getSendertype() {
        return sendertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.senderType
     *
     * @param sendertype the value for comment.senderType
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setSendertype(String sendertype) {
        this.sendertype = sendertype == null ? null : sendertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.update_time
     *
     * @return the value of comment.update_time
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.update_time
     *
     * @param updateTime the value for comment.update_time
     *
     * @mbg.generated Sat Jan 19 21:03:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}