package com.huaruan.shop.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table conversation
 *
 * @mbg.generated do_not_delete_during_merge Sun Jan 06 23:29:19 CST 2019
 */
public class ConversationDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.id
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.vendorid
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private Long vendorid;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.userid
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private Long userid;

    /**
     * Database Column Remarks:
     *   对话内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.content
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private Long content;

    /**
     * Database Column Remarks:
     *   发送人 1商户 2用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.sendertype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private String sendertype;

    /**
     * Database Column Remarks:
     *   生成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.create_time
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.update_time
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.id
     *
     * @return the value of conversation.id
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.id
     *
     * @param id the value for conversation.id
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.vendorid
     *
     * @return the value of conversation.vendorid
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public Long getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.vendorid
     *
     * @param vendorid the value for conversation.vendorid
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public void setVendorid(Long vendorid) {
        this.vendorid = vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.userid
     *
     * @return the value of conversation.userid
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.userid
     *
     * @param userid the value for conversation.userid
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.content
     *
     * @return the value of conversation.content
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public Long getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.content
     *
     * @param content the value for conversation.content
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public void setContent(Long content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.sendertype
     *
     * @return the value of conversation.sendertype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public String getSendertype() {
        return sendertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.sendertype
     *
     * @param sendertype the value for conversation.sendertype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public void setSendertype(String sendertype) {
        this.sendertype = sendertype == null ? null : sendertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.create_time
     *
     * @return the value of conversation.create_time
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.create_time
     *
     * @param createTime the value for conversation.create_time
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.update_time
     *
     * @return the value of conversation.update_time
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.update_time
     *
     * @param updateTime the value for conversation.update_time
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}