package com.huaruan.shop.dao;

import com.huaruan.shop.bo.CommentBO;
import com.huaruan.shop.bo.CommentBOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    long countByExample(CommentBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int deleteByExample(CommentBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Delete({
        "delete from comment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Insert({
        "insert into comment (vendorid, userid, ",
        "productid, content, ",
        "senderType, create_time, ",
        "update_time)",
        "values (#{vendorid,jdbcType=BIGINT}, #{userid,jdbcType=BIGINT}, ",
        "#{productid,jdbcType=BIGINT}, #{content,jdbcType=VARCHAR}, ",
        "#{sendertype,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(CommentBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int insertSelective(CommentBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    List<CommentBO> selectByExample(CommentBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Select({
        "select",
        "id, vendorid, userid, productid, content, senderType, create_time, update_time",
        "from comment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.huaruan.shop.dao.CommentMapper.BaseResultMap")
    CommentBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommentBO record, @Param("example") CommentBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int updateByExample(@Param("record") CommentBO record, @Param("example") CommentBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int updateByPrimaryKeySelective(CommentBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Update({
        "update comment",
        "set vendorid = #{vendorid,jdbcType=BIGINT},",
          "userid = #{userid,jdbcType=BIGINT},",
          "productid = #{productid,jdbcType=BIGINT},",
          "content = #{content,jdbcType=VARCHAR},",
          "senderType = #{sendertype,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CommentBO record);
}