package com.huaruan.shop.dao;

import com.huaruan.shop.entity.ConversationDO;
import com.huaruan.shop.entity.ConversationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ConversationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    long countByExample(ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int deleteByExample(ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Delete({
        "delete from conversation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Insert({
        "insert into conversation (vendorid, userid, ",
        "content, sendertype, ",
        "create_time, update_time)",
        "values (#{vendorid,jdbcType=BIGINT}, #{userid,jdbcType=BIGINT}, ",
        "#{content,jdbcType=BIGINT}, #{sendertype,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int insertSelective(ConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    List<ConversationDO> selectByExample(ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Select({
        "select",
        "id, vendorid, userid, content, sendertype, create_time, update_time",
        "from conversation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.huaruan.shop.dao.ConversationDOMapper.BaseResultMap")
    ConversationDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") ConversationDO record, @Param("example") ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExample(@Param("record") ConversationDO record, @Param("example") ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(ConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Update({
        "update conversation",
        "set vendorid = #{vendorid,jdbcType=BIGINT},",
          "userid = #{userid,jdbcType=BIGINT},",
          "content = #{content,jdbcType=BIGINT},",
          "sendertype = #{sendertype,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ConversationDO record);
}