package com.huaruan.shop.dao;

import com.huaruan.shop.entity.OrderDO;
import com.huaruan.shop.entity.OrderDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    long countByExample(OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int deleteByExample(OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Delete({
        "delete from order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Insert({
        "insert into order (vendorid, userid, ",
        "productid, productname, ",
        "product_cash, product_num, ",
        "status, postage, ",
        "adress, receiver, ",
        "create_time, update_time)",
        "values (#{vendorid,jdbcType=BIGINT}, #{userid,jdbcType=BIGINT}, ",
        "#{productid,jdbcType=BIGINT}, #{productname,jdbcType=VARCHAR}, ",
        "#{productCash,jdbcType=INTEGER}, #{productNum,jdbcType=INTEGER}, ",
        "#{status,jdbcType=VARCHAR}, #{postage,jdbcType=INTEGER}, ",
        "#{adress,jdbcType=VARCHAR}, #{receiver,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    List<OrderDO> selectByExample(OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Select({
        "select",
        "id, vendorid, userid, productid, productname, product_cash, product_num, status, ",
        "postage, adress, receiver, create_time, update_time",
        "from order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.huaruan.shop.dao.OrderDOMapper.BaseResultMap")
    OrderDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderDO record, @Param("example") OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExample(@Param("record") OrderDO record, @Param("example") OrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Update({
        "update order",
        "set vendorid = #{vendorid,jdbcType=BIGINT},",
          "userid = #{userid,jdbcType=BIGINT},",
          "productid = #{productid,jdbcType=BIGINT},",
          "productname = #{productname,jdbcType=VARCHAR},",
          "product_cash = #{productCash,jdbcType=INTEGER},",
          "product_num = #{productNum,jdbcType=INTEGER},",
          "status = #{status,jdbcType=VARCHAR},",
          "postage = #{postage,jdbcType=INTEGER},",
          "adress = #{adress,jdbcType=VARCHAR},",
          "receiver = #{receiver,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderDO record);
}