package com.huaruan.shop.dao;

import com.huaruan.shop.entity.PicDO;
import com.huaruan.shop.entity.PicDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface PicDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    long countByExample(PicDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int deleteByExample(PicDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Delete({
        "delete from pic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Insert({
        "insert into pic (path, create_time, ",
        "update_time)",
        "values (#{path,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(PicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int insertSelective(PicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    List<PicDO> selectByExample(PicDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Select({
        "select",
        "id, path, create_time, update_time",
        "from pic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.huaruan.shop.dao.PicDOMapper.BaseResultMap")
    PicDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") PicDO record, @Param("example") PicDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExample(@Param("record") PicDO record, @Param("example") PicDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(PicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Update({
        "update pic",
        "set path = #{path,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PicDO record);
}