package com.huaruan.shop.dao;

import com.huaruan.shop.entity.ProductypeDO;
import com.huaruan.shop.entity.ProductypeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ProductypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    long countByExample(ProductypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int deleteByExample(ProductypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Delete({
        "delete from productype",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Insert({
        "insert into productype (typename, status, ",
        "create_time, update_time)",
        "values (#{typename,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ProductypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int insertSelective(ProductypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    List<ProductypeDO> selectByExample(ProductypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Select({
        "select",
        "id, typename, status, create_time, update_time",
        "from productype",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.huaruan.shop.dao.ProductypeDOMapper.BaseResultMap")
    ProductypeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductypeDO record, @Param("example") ProductypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExample(@Param("record") ProductypeDO record, @Param("example") ProductypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(ProductypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productype
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Update({
        "update productype",
        "set typename = #{typename,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ProductypeDO record);
}