package com.huaruan.shop.dao;

import com.huaruan.shop.bo.ProductInfoBO;
import com.huaruan.shop.bo.ProductInfoBOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ProductInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    long countByExample(ProductInfoBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int deleteByExample(ProductInfoBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Delete({
        "delete from productinfo",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Insert({
        "insert into productinfo (productname, price, ",
        "number, product_desc, ",
        "product_pic_id, vendorid, ",
        "postage, status, ",
        "create_time, update_time, ",
        "commentid)",
        "values (#{productname,jdbcType=VARCHAR}, #{price,jdbcType=INTEGER}, ",
        "#{number,jdbcType=INTEGER}, #{productDesc,jdbcType=VARCHAR}, ",
        "#{productPicId,jdbcType=VARCHAR}, #{vendorid,jdbcType=BIGINT}, ",
        "#{postage,jdbcType=INTEGER}, #{status,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{commentid,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ProductInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int insertSelective(ProductInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    List<ProductInfoBO> selectByExample(ProductInfoBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Select({
        "select",
        "id, productname, price, number, product_desc, product_pic_id, vendorid, postage, ",
        "status, create_time, update_time, commentid",
        "from productinfo",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.huaruan.shop.dao.ProductInfoDOMapper.BaseResultMap")
    ProductInfoBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductInfoBO record, @Param("example") ProductInfoBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int updateByExample(@Param("record") ProductInfoBO record, @Param("example") ProductInfoBOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    int updateByPrimaryKeySelective(ProductInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Mon Jan 07 13:03:39 CST 2019
     */
    @Update({
        "update productinfo",
        "set productname = #{productname,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=INTEGER},",
          "number = #{number,jdbcType=INTEGER},",
          "product_desc = #{productDesc,jdbcType=VARCHAR},",
          "product_pic_id = #{productPicId,jdbcType=VARCHAR},",
          "vendorid = #{vendorid,jdbcType=BIGINT},",
          "postage = #{postage,jdbcType=INTEGER},",
          "status = #{status,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "commentid = #{commentid,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ProductInfoBO record);
}