package com.huaruan.shop.dao;

import com.huaruan.shop.entity.SysOrderDO;
import com.huaruan.shop.entity.SysOrderDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface SysOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    long countByExample(SysOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int deleteByExample(SysOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    @Insert({
        "insert into sys_order (vendor_id, user_id, ",
        "product_id, product_name, ",
        "product_cash, product_num, ",
        "status, postage, ",
        "adress, receiver_name, ",
        "create_time, update_time)",
        "values (#{vendorId,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{productId,jdbcType=BIGINT}, #{productName,jdbcType=VARCHAR}, ",
        "#{productCash,jdbcType=INTEGER}, #{productNum,jdbcType=INTEGER}, ",
        "#{status,jdbcType=VARCHAR}, #{postage,jdbcType=INTEGER}, ",
        "#{adress,jdbcType=VARCHAR}, #{receiverName,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SysOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int insertSelective(SysOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    List<SysOrderDO> selectByExample(SysOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysOrderDO record, @Param("example") SysOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_order
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int updateByExample(@Param("record") SysOrderDO record, @Param("example") SysOrderDOExample example);
}