package com.huaruan.shop.dao;

import com.huaruan.shop.entity.SysUserDO;
import com.huaruan.shop.entity.SysUserDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    long countByExample(SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int deleteByExample(SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    @Insert({
        "insert into sys_user (realname, username, ",
        "password, pic_id, ",
        "phone, role_id, sex, ",
        "desc, create_time, ",
        "update_time)",
        "values (#{realname,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{picId,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{roleId,jdbcType=VARCHAR}, #{sex,jdbcType=VARCHAR}, ",
        "#{desc,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int insertSelective(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    List<SysUserDO> selectByExample(SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysUserDO record, @Param("example") SysUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int updateByExample(@Param("record") SysUserDO record, @Param("example") SysUserDOExample example);
}