package com.huaruan.shop.dao;

import com.huaruan.shop.entity.UserVendorConversationDO;
import com.huaruan.shop.entity.UserVendorConversationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface UserVendorConversationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vendor_conversation
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    long countByExample(UserVendorConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vendor_conversation
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int deleteByExample(UserVendorConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vendor_conversation
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    @Insert({
        "insert into user_vendor_conversation (vendor_id, user_id, ",
        "content, sender_type, ",
        "create_time, update_time)",
        "values (#{vendorId,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{content,jdbcType=BIGINT}, #{senderType,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(UserVendorConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vendor_conversation
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int insertSelective(UserVendorConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vendor_conversation
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    List<UserVendorConversationDO> selectByExample(UserVendorConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vendor_conversation
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserVendorConversationDO record, @Param("example") UserVendorConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vendor_conversation
     *
     * @mbg.generated Sun Jan 27 17:07:06 CST 2019
     */
    int updateByExample(@Param("record") UserVendorConversationDO record, @Param("example") UserVendorConversationDOExample example);
}