package com.huaruan.shop.dao;

import com.huaruan.shop.entity.UserInfoDO;
import com.huaruan.shop.entity.UserInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    long countByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int deleteByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Delete({
        "delete from userinfo",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Insert({
        "insert into userinfo (name, account, ",
        "pwd, headpic, phone, ",
        "accountType, sex, ",
        "desc, create_time, ",
        "update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{account,jdbcType=VARCHAR}, ",
        "#{pwd,jdbcType=VARCHAR}, #{headpic,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
        "#{accounttype,jdbcType=VARCHAR}, #{sex,jdbcType=VARCHAR}, ",
        "#{desc,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int insertSelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    List<UserInfoDO> selectByExample(UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Select({
        "select",
        "id, name, account, pwd, headpic, phone, accountType, sex, desc, create_time, ",
        "update_time",
        "from userinfo",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.huaruan.shop.dao.UserInfoDOMapper.BaseResultMap")
    UserInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserInfoDO record, @Param("example") UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByExample(@Param("record") UserInfoDO record, @Param("example") UserInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 06 23:29:19 CST 2019
     */
    @Update({
        "update userinfo",
        "set name = #{name,jdbcType=VARCHAR},",
          "account = #{account,jdbcType=VARCHAR},",
          "pwd = #{pwd,jdbcType=VARCHAR},",
          "headpic = #{headpic,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "accountType = #{accounttype,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=VARCHAR},",
          "desc = #{desc,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserInfoDO record);
}